const stocks = [
    {name: "Газпром", sector: "Энергетика", price: 300, change: 1.2, index: "IMOEX", capitalization: 8000, pe: 4.5, ps: 1.2},
    {name: "Сбербанк", sector: "Финансы", price: 280, change: 0.5, index: "IMOEX", capitalization: 7000, pe: 6.2, ps: 2.0},
    {name: "Лукойл", sector: "Нефть и газ", price: 4500, change: -0.3, index: "IMOEX", capitalization: 5500, pe: 5.0, ps: 1.1},
    {name: "Норицкель", sector: "Металлургия", price: 15000, change: 0.7, index: "IMOEX", capitalization: 4500, pe: 8.0, ps: 3.2},
    {name: "Роснефть", sector: "Нефть и газ", price: 520, change: -0.1, index: "IMOEX", capitalization: 6000, pe: 6.8, ps: 1.5},
    {name: "Магнит", sector: "Ритейл", price: 5100, change: 1.8, index: "IMOEX", capitalization: 1000, pe: 10.1, ps: 0.8},
    {name: "Аэрофлот", sector: "Транспорт", price: 70, change: -1.2, index: "IMOEX", capitalization: 300, pe: 7.5, ps: 0.5},
    {name: "Яндекс", sector: "Технологии", price: 3000, change: 2.5, index: "IMOEX", capitalization: 2000, pe: 50.0, ps: 4.5},
    {name: "Татнефть", sector: "Нефть и газ", price: 720, change: -0.5, index: "IMOEX", capitalization: 700, pe: 5.6, ps: 1.3},
    {name: "Полюс", sector: "Золото", price: 17500, change: 1.0, index: "IMOEX", capitalization: 1200, pe: 7.0, ps: 2.2},
    {name: "ФосАгро", sector: "Химия", price: 4500, change: 0.4, index: "IMOEX", capitalization: 900, pe: 9.2, ps: 2.0},
    {name: "Сургутнефтегаз", sector: "Нефть и газ", price: 40, change: -0.2, index: "IMOEX", capitalization: 500, pe: 4.2, ps: 0.9},
    {name: "Интер РАО", sector: "Энергетика", price: 5, change: 0.6, index: "IMOEX", capitalization: 300, pe: 8.0, ps: 0.6},
    {name: "ВТБ", sector: "Финансы", price: 0.03, change: -0.4, index: "IMOEX", capitalization: 1500, pe: 3.5, ps: 1.1},
    {name: "Мосэнерго", sector: "Энергетика", price: 3.5, change: 0.8, index: "IMOEX", capitalization: 200, pe: 5.0, ps: 0.7},
    {name: "МТС", sector: "Телекоммуникации", price: 320, change: 0.9, index: "IMOEX", capitalization: 1000, pe: 6.5, ps: 1.8},
    {name: "Башнефть", sector: "Нефть и газ", price: 1600, change: -0.3, index: "IMOEX", capitalization: 500, pe: 5.3, ps: 1.2},
    {name: "Русал", sector: "Металлургия", price: 0.6, change: 1.3, index: "IMOEX", capitalization: 600, pe: 9.8, ps: 0.5},
    {name: "АЛРОСА", sector: "Добыча алмазов", price: 90, change: 0.7, index: "IMOEX", capitalization: 900, pe: 12.0, ps: 3.0},
    {name: "Юнипро", sector: "Энергетика", price: 2.7, change: -0.1, index: "IMOEX", capitalization: 350, pe: 6.5, ps: 1.1},
    {name: "Россети", sector: "Энергетика", price: 1.5, change: 0.4, index: "IMOEX", capitalization: 250, pe: 5.2, ps: 0.6},
    {name: "Транснефть", sector: "Транспорт нефти", price: 152000, change: 0.2, index: "IMOEX", capitalization: 3200, pe: 9.1, ps: 2.4},
    {name: "Северсталь", sector: "Металлургия", price: 2100, change: -0.4, index: "IMOEX", capitalization: 1600, pe: 5.4, ps: 1.7},
    {name: "Мечел", sector: "Металлургия", price: 80, change: 1.0, index: "IMOEX", capitalization: 400, pe: 6.8, ps: 0.5},
    {name: "Энел Россия", sector: "Энергетика", price: 1.2, change: -0.5, index: "IMOEX", capitalization: 100, pe: 4.8, ps: 0.9},
    {name: "ТГК-1", sector: "Энергетика", price: 0.02, change: 0.3, index: "IMOEX", capitalization: 50, pe: 3.5, ps: 0.2},
    {name: "ФСК ЕЭС", sector: "Энергетика", price: 0.1, change: 0.2, index: "IMOEX", capitalization: 600, pe: 5.9, ps: 0.4},
    {name: "Детский мир", sector: "Ритейл", price: 120, change: 1.5, index: "IMOEX", capitalization: 80, pe: 12.5, ps: 0.9},
    {name: "ПИК", sector: "Недвижимость", price: 450, change: 0.4, index: "IMOEX", capitalization: 900, pe: 7.5, ps: 1.1},
    {name: "Группа ЛСР", sector: "Недвижимость", price: 900, change: 0.9, index: "IMOEX", capitalization: 200, pe: 5.2, ps: 0.7},
    {name: "ОГК-2", sector: "Энергетика", price: 0.5, change: 0.3, index: "IMOEX", capitalization: 150, pe: 4.9, ps: 0.8},
    {name: "РЖД", sector: "Транспорт", price: 1400, change: 1.0, index: "IMOEX", capitalization: 1000, pe: 8.2, ps: 1.4},
    {name: "Эталон", sector: "Недвижимость", price: 50, change: 2.1, index: "IMOEX", capitalization: 60, pe: 3.8, ps: 0.5},
    {name: "Фармстандарт", sector: "Фармацевтика", price: 700, change: 0.4, index: "IMOEX", capitalization: 250, pe: 6.0, ps: 1.3},
    {name: "НЛМК", sector: "Металлургия", price: 210, change: 0.8, index: "IMOEX", capitalization: 500, pe: 9.3, ps: 1.2},
    {name: "КамАЗ", sector: "Автопром", price: 90, change: 1.7, index: "IMOEX", capitalization: 70, pe: 5.7, ps: 0.6},
    {name: "Росгосстрах", sector: "Страхование", price: 10, change: 0.5, index: "IMOEX", capitalization: 150, pe: 7.0, ps: 0.9},
    {name: "Северная звезда", sector: "Золото", price: 9500, change: 1.3, index: "IMOEX", capitalization: 1100, pe: 7.3, ps: 2.0},
    {name: "Обувь России", sector: "Ритейл", price: 5, change: 0.6, index: "IMOEX", capitalization: 100, pe: 4.2, ps: 0.7},
    {name: "Почта России", sector: "Логистика", price: 75, change: -0.3, index: "IMOEX", capitalization: 400, pe: 6.1, ps: 1.1},
    {name: "Балтика", sector: "Пищевая промышленность", price: 70, change: 1.2, index: "IMOEX", capitalization: 200, pe: 5.8, ps: 1.0},
    {name: "Открытие", sector: "Финансы", price: 150, change: -0.1, index: "IMOEX", capitalization: 800, pe: 5.5, ps: 1.3},
    {name: "РуссНефть", sector: "Нефть и газ", price: 400, change: 0.7, index: "IMOEX", capitalization: 600, pe: 7.2, ps: 1.4},
    {name: "Ренессанс Капитал", sector: "Финансы", price: 120, change: 0.9, index: "IMOEX", capitalization: 500, pe: 6.8, ps: 1.5},
    {name: "Аппи", sector: "Ритейл", price: 3500, change: 0.8, index: "IMOEX", capitalization: 1200, pe: 7.1, ps: 0.9},
    {name: "Юлмарт", sector: "Финансы", price: 180, change: -0.2, index: "IMOEX", capitalization: 1300, pe: 6.9, ps: 1.7},
    {name: "ВымпелКом", sector: "Телекоммуникации", price: 280, change: 1.0, index: "IMOEX", capitalization: 900, pe: 5.6, ps: 1.3},
    {name: "Русский Уголь", sector: "Уголь", price: 180, change: -0.4, index: "IMOEX", capitalization: 450, pe: 6.2, ps: 1.8},
    {name: "Почта Банк", sector: "Финансы", price: 25, change: 0.5, index: "IMOEX", capitalization: 700, pe: 4.3, ps: 1.2},
    {name: "Тамбовский бензин", sector: "Агропромышленность", price: 30, change: 0.6, index: "IMOEX", capitalization: 300, pe: 5.4, ps: 0.9}
];

export default stocks;